<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use App\Traits\CustomLogsActivity;

class Purchase extends Model
{
    use HasFactory, LogsActivity, CustomLogsActivity;

    protected string $customLogName = 'purchase';


    protected $fillable = [
        'supplier_id',
        'user_id',
        'reference_no',
        'purchase_date',
        'purchasing_status',
        'location_id',
        'pay_term',
        'pay_term_type',
        'attached_document',
        'total',
        'discount_type',
        'discount_amount',
        'final_total',
        'payment_status',
        'total_paid',
        // Supplier free claim columns
        'purchase_type',       // regular | free_claim | free_claim_standalone
        'claim_reference_id',  // FK → purchases.id (the original purchase that generated the claim)
        'claim_status',        // pending | partial | fulfilled (set when claim_free_quantity > 0)
        // Note: total_due is auto-generated by database
    ];

    // Removed appends since total_due is now a database column
    // protected $appends = ['total_due'];


    public function supplier()
    {
        return $this->belongsTo(Supplier::class);
    }

    public function location()
    {
        return $this->belongsTo(Location::class);
    }

    public function purchaseProducts()
    {
        return $this->hasMany(PurchaseProduct::class);
    }

    public function payments()
    {
        return $this->hasMany(Payment::class, 'reference_id', 'id')->where('payment_type', 'purchase');
    }

    // ---- Supplier Free Claim Relationships ----

    /**
     * Free claim receipt purchases that deliver against this purchase's promised qty.
     * e.g. if this is PO-001 with claim_free_quantity=10, these are the zero-cost
     * purchases created when the supplier delivered the free items.
     */
    public function claimReceipts()
    {
        return $this->hasMany(Purchase::class, 'claim_reference_id');
    }

    /**
     * The original purchase this free_claim receipt is delivering against.
     */
    public function originalClaim()
    {
        return $this->belongsTo(Purchase::class, 'claim_reference_id');
    }

    /**
     * Total qty already received (across all partial receipts) for a given product.
     * Remaining = purchase_products.claim_free_quantity - receivedClaimQty($productId)
     */
    public function receivedClaimQty(int $productId): float
    {
        return (float) $this->claimReceipts()
            ->join('purchase_products', 'purchases.id', '=', 'purchase_products.purchase_id')
            ->where('purchase_products.product_id', $productId)
            ->sum('purchase_products.quantity');
    }

    // Removed getTotalPaidAttribute() since total_paid is now a database column
    // Removed getTotalDueAttribute() since total_due is auto-generated by database

    // Update the total paid amount (total_due auto-calculates)
    public function updateTotalDue()
    {
        $this->total_paid = $this->payments()->sum('amount');
        $this->save(); // total_due will auto-calculate
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
