<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use App\Traits\CustomLogsActivity;

class Purchase extends Model
{
    use HasFactory, LogsActivity, CustomLogsActivity;

    protected string $customLogName = 'purchase';


    protected $fillable = [
        'supplier_id',
        'user_id',
        'reference_no',
        'purchase_date',
        'purchasing_status',
        'location_id',
        'pay_term',
        'pay_term_type',
        'attached_document',
        'total',
        'discount_type',
        'discount_amount',
        'final_total',
        'payment_status',
        'total_paid'
        // Note: total_due is auto-generated by database
    ];

    // Removed appends since total_due is now a database column
    // protected $appends = ['total_due'];


    public function supplier()
    {
        return $this->belongsTo(Supplier::class);
    }

    public function location()
    {
        return $this->belongsTo(Location::class);
    }

    public function purchaseProducts()
    {
        return $this->hasMany(PurchaseProduct::class);
    }

    public function payments()
    {
        return $this->hasMany(Payment::class, 'reference_id', 'id')->where('payment_type', 'purchase');
    }

    // Removed getTotalPaidAttribute() since total_paid is now a database column
    // Removed getTotalDueAttribute() since total_due is auto-generated by database

    // Update the total paid amount (total_due auto-calculates)
    public function updateTotalDue()
    {
        $this->total_paid = $this->payments()->sum('amount');
        $this->save(); // total_due will auto-calculate
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
